name: CI/CD Build and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: cd enterpro_app && npm install

    - name: List files in enterpro_app
      run: ls -la enterpro_app

    - name: Run Tests
      run: cd enterpro_app && npm test

    - name: Build Application
      run: cd enterpro_app && npm run build

    - name: Run Lint
      run: cd enterpro_app && npm run lint || true